CREATE TABLE `prolific` (
	`submission_id` text PRIMARY KEY NOT NULL,
	`participant_id` text NOT NULL,
	`status` text,
	`custom_study_tncs_accepted_at` text,
	`started_at` text,
	`completed_at` text,
	`reviewed_at` text,
	`archived_at` text,
	`time_taken` text,
	`completion_code` text,
	`total_approvals` text,
	`gender` text,
	`highest_education_level_completed` text,
	`age` text,
	`sex` text,
	`ethnicity_simplified` text,
	`country_of_birth` text,
	`country_of_residence` text,
	`nationality` text,
	`language` text,
	`student_status` text,
	`employment_status` text
);
